version: '2'
services:
  connect:
    image: quay.io/debezium/connect:2.1
    ports:
     - 8083:8083
    restart: always
    environment:
     - GROUP_ID=1
     - BOOTSTRAP_SERVERS=kafka:9092
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
  connect-ui:
    image: landoop/kafka-connect-ui
    ports:
      - 8000:8000
    links:
     - connect
    environment:
      - CONNECT_URL=connect:8083

networks: 
  default: 
      name: kafka-net
      external: true